name: "retriever_ctx"
backend: "onnxruntime"
default_model_filename: "ctx_quant_percential_calib.onnx"


max_batch_size: 1
optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP32" }
    parameters { key: "max_workspace_size_bytes" value: "1073741824" }
    }]
}}